# Generated by Django 4.2.3 on 2023-09-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='post_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
