# Generated by Django 4.2.3 on 2023-09-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_thread_post_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='short_title',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
